llm:
  provider: groq  # Default provider
  models:
    groq:
      default: llama3-8b-8192
      options:
        - llama3-8b-8192
        - llama3-70b-8192
        - mixtral-8x7b-32768
    openai:
      default: gpt-4o
      options:
        - gpt-4o
        - gpt-4o-mini
        - gpt-3.5-turbo
    anthropic:
      default: claude-3-5-sonnet-20240620
      options:
        - claude-3-5-sonnet-20240620
        - claude-3-opus-20240229
        - claude-3-haiku-20240307

# Agent configurations
agents:
  default: basic_llm  # Default agent to use
  definitions:
    basic_llm:
      description: "Simple LLM-based agent without tools"
      type: "basic"
      provider: "groq"
      model: "llama3-8b-8192"
      temperature: 0.7
      
    paper_researcher:
      description: "Scientific paper research agent using arXiv"
      type: "tool_augmented"
      provider: "groq"
      model: "llama3-8b-8192"
      temperature: 0.3
      prompt_template: "You are a scientific paper researcher. Answer questions about papers or retrieve papers on {request}. Be concise and focus on the most relevant information."
      tools:
        - "arxiv"
        
    web_researcher:
      description: "Web search agent with Google Search"
      type: "tool_augmented"
      provider: "anthropic"
      model: "claude-3-5-sonnet-20240620"
      temperature: 0.2
      prompt_template: "You are a web researcher who helps users find information online. Research {request} and provide a concise summary of the most relevant information."
      tools:
        - "google_search"
        
    code_assistant:
      description: "Programming assistant with access to documentation"
      type: "tool_augmented"
      provider: "openai"
      model: "gpt-4o"
      temperature: 0.1
      prompt_template: "You are a helpful programming assistant. Help with {request} by writing code, explaining concepts, or looking up documentation."
      tools:
        - "python_repl"
        - "terminal"

# CDP wallet configuration
wallet:
  consumer_id: 3e4c9f11-18a3-4905-a474-777909c5736d
  provider_id: e5b34cf5-df25-4ceb-8b81-8d0036f7d8ef
  asset_id: usdc
  gasless: false

# Paths configuration
paths:
  cdp_api: api-key/cdp_api_key.json
  consumer_seed: wallets/consumer_seed.json
  provider_seed: wallets/provider_seed.json 